### ISSUE TITLE
Strange Error even though no using Inspire Pack nodes in API workflow.

### ISSUE THREAD

**Issue by caniyabanci76** [ltdrdata/ComfyUI-Inspire-Pack#11]
Hi, I am running an XY plot workflow via API, although the workflow contains no Inspire Pack nodes, I get the following message when the script starts (the script does continue and complete without problems though)

```
got prompt
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "/home/jh/ai/ComfyUI/server.py", line 625, in trigger_on_prompt
    json_data = handler(json_data)
  File "/home/jh/ai/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/inspire_server.py", line 122, in onprompt
    is_changed = prompt_seed_update(json_data)
  File "/home/jh/ai/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/inspire_server.py", line 63, in prompt_seed_update
    seed_widget_map = json_data['extra_data']['extra_pnginfo']['workflow']['seed_widgets']
KeyError: 'extra_data'
```

**Comment by ltdrdata** [comment]
I didnt' considered API mode.

Fixed on e471ed8b1745e03c3f400866a7d650230383bdb5
Just GlobalSeed isn't supported on API mode.
