### ISSUE TITLE
ImportError: cannot import name 'CFGGuider' from 'comfy.samplers' (E:\ComfyUI-aki-v1.1\comfy\samplers.py)

### ISSUE THREAD

**Issue by Charlo-O** [ltdrdata/ComfyUI-Inspire-Pack#122]
### Loading: ComfyUI-Inspire-Pack (V0.82)
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.1\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Inspire-Pack\__init__.py", line 34, in <module>
    imported_module = importlib.import_module(".inspire.{}".format(module_name), __name__)
  File "E:\ComfyUI-aki-v1.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Inspire-Pack\inspire\sampler_nodes.py", line 6, in <module>
    from comfy.samplers import CFGGuider
ImportError: cannot import name 'CFGGuider' from 'comfy.samplers' (E:\ComfyUI-aki-v1.1\comfy\samplers.py)

Cannot import E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Inspire-Pack module for custom nodes: cannot import name 'CFGGuider' from 'comfy.samplers' (E:\ComfyUI-aki-v1.1\comfy\samplers.py)

**Comment by ltdrdata** [comment]
You have to update ComfyUI to latest version.

**Comment by Charlo-O** [comment]
i

> You have to update ComfyUI to latest version.

1 switch to thean old version，
