### ISSUE TITLE
Error occurred when executing UnzipPrompt //Inspire:  UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

### ISSUE THREAD

**Issue by neozbr** [ltdrdata/ComfyUI-Inspire-Pack#124]
Error occurred when executing UnzipPrompt //Inspire:

UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

can someone help please

**Comment by ltdrdata** [comment]
Show me the screenshot of the workflow.

**Comment by ltdrdata** [comment]
> I have this error too. Here's the screenshot: ![comfy_error](https://private-user-images.githubusercontent.com/140403375/349468927-f62862c6-9d86-48ed-b22c-5987882a9a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjcxMTEsIm5iZiI6MTcyMTQ2NjgxMSwicGF0aCI6Ii8xNDA0MDMzNzUvMzQ5NDY4OTI3LWY2Mjg2MmM2LTlkODYtNDhlZC1iMjJjLTU5ODc4ODJhOWE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwOTEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjI0OGJlYjk4ZWIzYWM1Y2U1M2NjNjAwMzg5ZDFjYjg4YmJkYTEzZTM5ZmM0NzgzOWEyNjgyYjJkNTVmYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r_Tjg2lZte445wVChLEnqG7F9OJCPXMrQX6USjopxqc)

![image](https://github.com/user-attachments/assets/a657cc37-7ffc-4e5f-af66-fe8b0c04efd8)

What is your `Inspire Pack` version?

**Comment by neozbr** [comment]
here's the screenshot 
![error](https://github.com/user-attachments/assets/5d5ba446-769c-41e8-904e-0969b036428b)

**Comment by 1manfactory** [comment]
Same problem here. Even with the provided demo files.
Workflow used to work 2 week ago before I updated.

![image](https://github.com/user-attachments/assets/7c419f1c-ebc6-4f21-bc06-e91d0d3e150b)

**Comment by neozbr** [comment]
exactly really used to work... I really like comfyui but those updates are a huge headaches sometimes...

**Comment by ltdrdata** [comment]
Disable all other custom nodes and try again. There is a possibility of conflict with other custom nodes.

**Comment by ltdrdata** [comment]
> I had this error without any other custom nodes installed. Only this Inspire Pack.

Open `prompt_support.py` file in text editor and show me the line 225.

![image](https://github.com/user-attachments/assets/e8884d8f-9af0-4446-816e-ee2e48755cd7)

**Comment by ltdrdata** [comment]
> Files are identical to commit "cadf604" Nothing is modified ![comfy_error_02](https://private-user-images.githubusercontent.com/140403375/350729332-1ec80452-10fd-4439-a724-6b2a9c175f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzE0OTgsIm5iZiI6MTcyMTUzMTE5OCwicGF0aCI6Ii8xNDA0MDMzNzUvMzUwNzI5MzMyLTFlYzgwNDUyLTEwZmQtNDQzOS1hNzI0LTZiMmE5YzE3NWY0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwMzA2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTU3YWE4Y2QzNWQ5NjIzNjcxMWQzZjdjYTUzMzQyYjdmOGRiNTk5M2Y0YTMzMWE5MWYyNThkNDMzNDVlNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b1qP5YylFUE8OxN4gRP1iAg9fCBpRl_9itxihHCK5UE)

Send me the your workflow. It seems I need to test whether the workflow reproduces that issue.

**Comment by george7551858** [comment]
https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/c90d6c8d0f8b5d83eb1b37143a9de1338ee94788/inspire/prompt_support.py#L185
Change this line to

```python
  if not text_data_opt:
``` 
could resolve this issue.

**Comment by ltdrdata** [comment]
> george7551858

oh.... my fault...
this is fixed.

**Comment by sirohijai22** [comment]
I am getting the same error with latest version.
Disabled all other custom nodes, still inable to make it run.
Below is the error and workflow:


2025-01-17T12:30:51.994995 - Prompt executed in 0.01 seconds
2025-01-17T12:32:30.105828 - FETCH DATA from: E:\Work\Jai\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-01-17T12:32:30.105828 - 2025-01-17T12:32:30.108947 -  [DONE]2025-01-17T12:32:30.108947 - 
2025-01-17T12:32:30.133545 - FETCH DATA from: https://api.comfy.org/nodes?page=1&limit=10002025-01-17T12:32:30.134055 - 2025-01-17T12:32:37.571997 -  [DONE]2025-01-17T12:32:37.571997 - 
2025-01-17T12:32:37.704664 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes?page=1&limit=10002025-01-17T12:32:37.704664 - 
2025-01-17T12:32:37.710423 - nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache
2025-01-17T12:32:37.710423 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-01-17T12:32:37.710423 - 2025-01-17T12:32:38.022114 -  [DONE]2025-01-17T12:32:38.022114 - 
2025-01-17T12:32:41.096862 - got prompt
2025-01-17T12:32:41.101862 - !!! Exception during processing !!! UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'
2025-01-17T12:32:41.103365 - Traceback (most recent call last):
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 170, in _map_node_over_list
    process_inputs({})
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
TypeError: UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

2025-01-17T12:32:41.104370 - Prompt executed in 0.00 seconds
2025-01-17T12:32:47.265476 - got prompt
2025-01-17T12:32:47.271986 - !!! Exception during processing !!! UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'
2025-01-17T12:32:47.271986 - Traceback (most recent call last):
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 170, in _map_node_over_list
    process_inputs({})
  File "E:\Work\Jai\pinokio\api\comfy.git\app\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
TypeError: UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

2025-01-17T12:32:47.273500 - Prompt executed in 0.00 seconds

![Image](https://github.com/user-attachments/assets/03d82d76-ee92-4378-ae48-291f9eb8c7ac)

Could you please help.

**Comment by ltdrdata** [comment]
> u/[ltdrdata](https://github.com/ltdrdata) I had the same error today, though 2 days ago it was fine and nothing changed, I reinstalled the Custom Node but nothing happened, here's a screenshot of line 255 in the prompt_support.py
> 
> <img alt="Image" width="1161" height="57" src="https://private-user-images.githubusercontent.com/41054899/465282595-b9b723f3-f7b8-4672-9d85-c3f1c1dddbd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIyNjcyNTEsIm5iZiI6MTc1MjI2Njk1MSwicGF0aCI6Ii80MTA1NDg5OS80NjUyODI1OTUtYjliNzIzZjMtZjdiOC00NjcyLTlkODUtYzNmMWMxZGRkYmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzExVDIwNDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjdkYTU3MTYyZDQ0ZDQ2OWIyZjU3NzY0YWNjMWFjNmJlYTdiNDg3ZTA5NTRkNDQ5ZDEyNWI0OTZhZmZkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K46DdRZX9_ULAtJ2R2zyXVXWVuOItdvEb9J1S_Jz5dw">

Your issue doesn't seem to be related to this error.
Please share the log messages.

**Comment by EGBluesman** [comment]
I guess it's related to the txt file. To make it work I copied the positive
and negative prompts into the example prompt2 file.

**Comment by EGBluesman** [comment]
I am sorry here's the log screenshot

[image: image.png]
