### ISSUE TITLE
After updating ComfyUI, the node fails

### ISSUE THREAD

**Issue by Edward-keyes** [ltdrdata/ComfyUI-Inspire-Pack#155]
After updating ComfyUI, the node fails, updating the node does not help, and it still cannot be used

**Comment by ltdrdata** [comment]
Show me the full log.

**Comment by Edward-keyes** [comment]
> Show me the full log.

Multiple attempts to update still indicate that the Image2Text node is missing

**Comment by Edward-keyes** [comment]
The log is as follows. In fact, at the very back you can see "Loading: ComfyUI-Inspire-Pack (V1.1)".But it's still missing nodes

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-05 15:23:47.272027
** Platform: Linux
** Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
** Python executable: /root/miniconda3/bin/python
** ComfyUI Path: /root/autodl-tmp/ComfyUI
** Log path: /root/autodl-tmp/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.9 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Manager

### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2081 [6a32c06f] | Released on '2024-03-23'
### Loading: ComfyUI-Impact-Pack (V7.4.1)
### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)

[bold yellow]WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/../../` as the ComfyUI path.[/bold yellow]

[bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/root/autodl-tmp/ComfyUI/models` as the ComfyUI path.[/bold yellow]
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[Impact Pack] EXECUTE: ['/root/miniconda3/bin/python', 'install.py'] in '/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/root/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/install.py", line 30, in <module>
    download_url("https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt",
  File "/root/miniconda3/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 134, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/root/miniconda3/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 82, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
req_path: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
/root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
------------------------------------------
[34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
# 😺dzNodes: LayerStyle -> [1;33mCannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to [4mhttps://github.com/chflame163/ComfyUI_LayerStyle/issues/5[0m[m
# 😺dzNodes: LayerStyle -> [1;33mWarning: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_LayerStyle/resource_dir.ini not found, default directory to be used. [m
# 😺dzNodes: LayerStyle -> [1;33mFind 1 LUTs in /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_LayerStyle/lut[m
# 😺dzNodes: LayerStyle -> [1;33mFind 1 Fonts in /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_LayerStyle/font[m
json_repair## OK
/root/miniconda3/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: [1mThe TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.[0m
  warnings.warn(problem)
/root/miniconda3/lib/python3.10/site-packages/torchvision/datapoints/__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
/root/miniconda3/lib/python3.10/site-packages/torchvision/transforms/v2/__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
simple_lama_inpainting## OK
## lama torchscript model not found: /root/autodl-tmp/ComfyUI/models/lama/big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
## clip_interrogator_model not found: /root/autodl-tmp/ComfyUI/models/clip_interrogator/Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
## text_generator_model not found: /root/autodl-tmp/ComfyUI/models/prompt_generator/text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: /root/autodl-tmp/ComfyUI/models/prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
Package diffusers is already installed.
[31mComfyui-ergouzi-DGNJD：[33m[39m
[34mWAS Node Suite: [0mBlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.[0m
[34mWAS Node Suite: [0m`CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.[0m
[34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `/root/autodl-tmp/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m219[0m [32mnodes successfully.[0m

	[3m[93m"Success is not final, failure is not fatal: It is the courage to continue that counts."[0m[3m - Winston Churchill[0m

tqdm is already installed.
Installing ImageReward...
Requirement already satisfied: image-reward in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (1.5)
Collecting timm==0.6.13 (from image-reward)
  Downloading timm-0.6.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: transformers>=4.27.4 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (4.38.2)
Requirement already satisfied: fairscale==0.4.13 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (0.4.13)
Requirement already satisfied: huggingface-hub>=0.13.4 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (0.23.4)
Requirement already satisfied: diffusers>=0.16.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (0.21.2)
Requirement already satisfied: accelerate>=0.16.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (0.30.1)
Requirement already satisfied: datasets>=2.11.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from image-reward) (2.19.1)
Requirement already satisfied: torch>=1.8.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from fairscale==0.4.13->image-reward) (2.0.1+cu117)
Requirement already satisfied: numpy>=1.22.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from fairscale==0.4.13->image-reward) (1.24.4)
Requirement already satisfied: torchvision in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from timm==0.6.13->image-reward) (0.15.2+cu117)
Requirement already satisfied: pyyaml in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from timm==0.6.13->image-reward) (6.0)
Requirement already satisfied: packaging>=20.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from accelerate>=0.16.0->image-reward) (23.2)
Requirement already satisfied: psutil in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from accelerate>=0.16.0->image-reward) (5.9.4)
Requirement already satisfied: safetensors>=0.3.1 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from accelerate>=0.16.0->image-reward) (0.4.2)
Requirement already satisfied: filelock in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (3.13.1)
Requirement already satisfied: pyarrow>=12.0.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (16.0.0)
Requirement already satisfied: pyarrow-hotfix in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (0.3.8)
Requirement already satisfied: pandas in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (4.64.1)
Requirement already satisfied: xxhash in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (3.4.1)
Requirement already satisfied: multiprocess in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (0.70.16)
Requirement already satisfied: fsspec<=2024.3.1,>=2023.1.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from fsspec[http]<=2024.3.1,>=2023.1.0->datasets>=2.11.0->image-reward) (2024.3.1)
Requirement already satisfied: aiohttp in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from datasets>=2.11.0->image-reward) (3.9.3)
Requirement already satisfied: importlib-metadata in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from diffusers>=0.16.0->image-reward) (7.1.0)
Requirement already satisfied: regex!=2019.12.17 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from diffusers>=0.16.0->image-reward) (2023.12.25)
Requirement already satisfied: Pillow in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from diffusers>=0.16.0->image-reward) (10.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from huggingface-hub>=0.13.4->image-reward) (4.10.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from transformers>=4.27.4->image-reward) (0.15.2)
Requirement already satisfied: aiosignal>=1.1.2 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from aiohttp->datasets>=2.11.0->image-reward) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (2024.6.2)
Requirement already satisfied: sympy in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (1.12)
Requirement already satisfied: networkx in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (3.2.1)
Requirement already satisfied: jinja2 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (2.0.0)
Requirement already satisfied: cmake in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->fairscale==0.4.13->image-reward) (3.29.2)
Requirement already satisfied: lit in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->fairscale==0.4.13->image-reward) (18.1.8)
Requirement already satisfied: zipp>=0.5 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from importlib-metadata->diffusers>=0.16.0->image-reward) (3.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from pandas->datasets>=2.11.0->image-reward) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from pandas->datasets>=2.11.0->image-reward) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from pandas->datasets>=2.11.0->image-reward) (2024.1)
Requirement already satisfied: six>=1.5 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.11.0->image-reward) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->fairscale==0.4.13->image-reward) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /root/autodl-tmp/miniconda3/lib/python3.10/site-packages (from sympy->torch>=1.8.0->fairscale==0.4.13->image-reward) (1.3.0)
Downloading timm-0.6.13-py3-none-any.whl (549 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.1/549.1 kB 19.3 MB/s eta 0:00:00
Installing collected packages: timm
  Attempting uninstall: timm
    Found existing installation: timm 0.9.16
    Uninstalling timm-0.9.16:
      Successfully uninstalled timm-0.9.16
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deepseek-vl 1.0.0 requires timm>=0.9.16, but you have timm 0.6.13 which is incompatible.
salesforce-lavis 1.0.2 requires fairscale==0.4.4, but you have fairscale 0.4.13 which is incompatible.
salesforce-lavis 1.0.2 requires opencv-python-headless==4.5.5.64, but you have opencv-python-headless 4.10.0.84 which is incompatible.
salesforce-lavis 1.0.2 requires timm==0.4.12, but you have timm 0.6.13 which is incompatible.
salesforce-lavis 1.0.2 requires transformers<4.27,>=4.25.0, but you have transformers 4.38.2 which is incompatible.
torchscale 0.3.0 requires fairscale==0.4.0, but you have fairscale 0.4.13 which is incompatible.
Successfully installed timm-0.6.13
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Pillow的当前版本10.4.0满足要求，无需安装10.1.0版本。
huggingface_hub的当前版本0.23.4满足要求，无需安装0.20.1版本。
auto-gptq的当前版本0.7.1满足要求，无需安装0.7.1版本。
einops的当前版本0.7.0满足要求，无需安装0.7.0版本。
torchvision is already installed.
accelerate的当前版本0.30.1满足要求，无需安装0.25.0版本。
timm的当前版本0.9.16满足要求，无需安装0.9.16版本。
autoawq的当前版本0.2.3满足要求，无需安装0.2.3版本。
tiktoken is already installed.
attrdict is already installed.
einops的当前版本0.7.0满足要求，无需安装0.7.0版本。
sentencepiece的当前版本0.2.0满足要求，无需安装0.2.0版本。
deepseek_vl is already installed.
transformers的当前版本4.38.2满足要求，无需安装4.38.2版本。
accelerate的当前版本0.30.1满足要求，无需安装0.29.3版本。
bitsandbytes的当前版本0.43.1满足要求，无需安装0.43.1版本。
Crypto is already installed.
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
here: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-tbox
Using ckpts path: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotator
Using symlinks: False
Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
here>> /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-tbox 
### Loading: ComfyUI-Inspire-Pack (V1.1)

**Comment by ltdrdata** [comment]
Your log doesn't contains related to Inspire Pack.
