### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_cpp'  

### ISSUE THREAD

**Issue by Cokeheart** [ltdrdata/ComfyUI-Inspire-Pack#188]
### Loading: ComfyUI-Inspire-Pack (V1.6)                                                                                          
Traceback (most recent call last):                                                                                                
  File "I:\ComfyUI-aki-v1.4\nodes.py", line 2022, in load_custom_node                                                             
    module_spec.loader.exec_module(module)                                                                                        
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                         
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                    
  File "I:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-LLaVA-Captioner\__init__.py", line 1, in <module>                                
    from .llava import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS                                                            
  File "I:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-LLaVA-Captioner\llava.py", line 12, in <module>                                  
    from llama_cpp import Llama                                                                                                   
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by ltdrdata** [comment]
This is not a issue of Inspire Pack.
Please move this issue to ComfyUI-LLaVA-Captioner repo.
https://github.com/ceruleandeep/ComfyUI-LLaVA-Captioner
