### ISSUE TITLE
Image refiner may need some refactoring

### ISSUE THREAD

**Issue by JAssertz** [ltdrdata/ComfyUI-Inspire-Pack#27]
Hey, I was messing around with image refiner last night and I noticed that it was encountering a few errors for example see exhibit 1 below and also noticed that after fixing it I encountered an issue of a missing function from comfyui's main model management set I don't think this is something related to my local install but it is possible will

exhibit 1
Traceback (most recent call last):
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 69, in imagerefiner_generate
    result = ir.generate(base_pil.convert('RGB'), mask_pil, prompt_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 174, in generate
    input_data_all = prepare_input(class_def, merged_pil, mask_pil, prompt_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 94, in prepare_input
    model, clip, vae = load_checkpoint(v['checkpoint'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 38, in load_checkpoint
    model, clip, vae, _ = comfy_nodes.CheckpointLoaderSimple().load_checkpoint(ckpt_name)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)

exhibit B
Traceback (most recent call last):
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\venv\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\AI\Stable-Diffusion\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 69, in imagerefiner_generate
    result = ir.generate(base_pil.convert('RGB'), mask_pil, prompt_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 177, in generate
    comfy.model_management.unload_model()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_management' has no attribute 'unload_model'

**Comment by JAssertz** [comment]
Opened on wrong repo reoppening on workflow-component

**Comment by ltdrdata** [comment]
Your workflow component is outdated version.
