### ISSUE TITLE
AttributeError: type object 'ImpactWildcardEncode' has no attribute 'get_wildcard_list'

### ISSUE THREAD

**Issue by stevens-Ai** [ltdrdata/ComfyUI-Inspire-Pack#29]
when starting comfyui I get this after all nodes are loaded:
```
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Ai_art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'WildcardEncode //Inspire' node.
Traceback (most recent call last):
  File "D:\Ai_art\ComfyUI_windows_portable\ComfyUI\server.py", line 417, in get_object_info
    out[x] = node_info(x)
  File "D:\Ai_art\ComfyUI_windows_portable\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\Ai_art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\prompt_support.py", line 318, in INPUT_TYPES
    wildcards = nodes.NODE_CLASS_MAPPINGS['ImpactWildcardEncode'].get_wildcard_list()
AttributeError: type object 'ImpactWildcardEncode' has no attribute 'get_wildcard_list'
```

**Comment by ltdrdata** [comment]
Update Impact Pact to latest version.

**Comment by stevens-Ai** [comment]
That fixed it.
Thanks
