### ISSUE TITLE
X/Y LoRA Block Weight Error

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#30]
Hitting a wall on a standard X/Y plot.  Would appreciate some help trying to get past whatever this is.  

```
Ckpt:
  [1] sd_xl_base_1.0
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\lora_block_weight.py", line 260, in doit
    model_lora, clip_lora, populated_vector = LoraLoaderBlockWeight.load_lora_for_models(model, clip, lora, strength_model, strength_clip, inverse, seed, A, B, block_vector)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\lora_block_weight.py", line 151, in load_lora_for_models
    raise ValueError(f"[LoraLoaderBlockWeight] invalid block_vector '{block_vector}'")
ValueError: [LoraLoaderBlockWeight] invalid block_vector 'A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B2'

Prompt executed in 24.10 seconds
```

**Comment by sedetweiler** [comment]
[workflow (26).json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/13182824/workflow.26.json)

**Comment by sedetweiler** [comment]
Sorry, figured it out.  Cheers!
