### ISSUE TITLE
Error - AttributeError: 'Logger' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by matichek** [ltdrdata/ComfyUI-Inspire-Pack#36]
Running windows 10.

The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "D:\Projects\comphy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 408, in <module>
    import impact.subpack_nodes
  File "D:\Projects\comphy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\Projects\comphy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
  File "D:\Projects\comphy\ComfyUI\env\lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
AttributeError: 'Logger' object has no attribute 'encoding'
---------------------------------

**Comment by ltdrdata** [comment]
Update `ComfyUI-Manager` to latest version.
