### ISSUE TITLE
Wilcards do not populate

### ISSUE THREAD

**Issue by BigBlueGX** [ltdrdata/ComfyUI-Inspire-Pack#44]
Wildcards do not load in the "Wilcard Encode (inspire)" of the Inspire Pack when I select "populate"

but they work on the "ImpactWilcardEncode" of the impact pack

this is what I get from the cmd:
__________________________________________________________________

got prompt
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 633, in trigger_on_prompt
    json_data = handler(json_data)
                ^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 203, in onprompt
    populate_wildcards(json_data)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 181, in populate_wildcards
    inputs['populated_text'] = wildcard_process(text=inputs['wildcard_text'], seed=int(inputs['seed']))
                                                                                   ^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
CLIP:
Requested to load BaseModel

__________________________________________________________________________________

**Comment by BigBlueGX** [comment]
Found the issue: 

It's an issue with the "Use Everywhere" nodes. "Seed Everywhere" does not give a proper seed.
It works when I use a primitive directly on the "Wilcard Encode (inspire)" to provide it with a seed.
