### ISSUE TITLE
Detailer Hands

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#5]
Just watched your video on hands, but am hitting an error.

!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1703, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 609, in do_detail
    enhanced_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 227, in enhance_detail
    positive = control_net_wrapper.apply(positive, upscaled_image)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1268, in apply
    image = self.preprocessor.apply(image)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\segs_support.py", line 37, in apply
    return obj.estimate_pose(image, detect_hand, detect_body, detect_face)[0]
KeyError: 0

**Comment by lellotrek** [comment]
Hello, i have the same issue

**Comment by ltdrdata** [comment]
> Hello, i have the same issue

This is fixed on 94acad47d7946e9493de2a0164248143e08f6756

**Comment by lellotrek** [comment]
thank you for this and all your work!
